# Inputs
#project.source: '/virgoData/ffl/raw_O3b_arch'
project.source: '/virgoData/ffl/trend.ffl'
project.decimate: false
#project.start_time: 1262680000
#project.start_time: 1262649600
project.start_time: 1256688000
#project.start_time: 1262655700
#project.end_time: 1262684200
#project.end_time: 1262700800
#project.end_time: 1262655700
project.end_time: 1256774400
project.target_frequency: 1
project.cutoff_frequency: 50
project.blacklist_patterns: './resources/blacklist_patterns.txt'

# Kerberos config
kerberos.username: menno.bruin
kerberos.keytab: .keytab