# Inputs
#project.source: '/virgoData/ffl/raw_O3b_arch.ffl'
project.source: '/virgoData/ffl/trend.ffl'
#project.source: 'local'
project.decimate: false
project.load_existing: false
project.run: true
project.channel: 'V1:ENV_WEB_MAG_N'
project.pipeline: 'omicron'
project.trigger_file: 'GSpy_ALLIFO_O3b_0921_final.csv'
project.start_time: 1262678418
project.end_time: 1262908818
project.target_frequency: 1
project.blacklist_patterns: './resources/blacklist_patterns.txt'



# Kerberos config
kerberos.username: menno.bruin
kerberos.keytab: .keytab