# Inputs
project.source: '/virgoData/ffl/raw_O3b_arch'
#project.start_time: 1262680000
#project.start_time: 1262649600
project.start_time: 1262649800
#project.end_time: 1262684200
#project.end_time: 1262700800
#project.end_time: 1262655700
project.end_time: 1262649900
project.target_frequency: 50
project.blacklist_patterns: './resources/blacklist_patterns.txt'

# Kerberos config
kerberos.username: menno.bruin
kerberos.keytab: .keytab